title: Alberto López Martín
logo: /assets/img/logo.png
description: Adjunct Assistant Professor <br> Department of Mathematics <br> ISEG, Universidade de Lisboa .
show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal
